### PR TITLE
Plot network statistics.

### PR DESCRIPTION
**Pull request by jdonkervliet**
Updated process guard to change network log file format. Makes it easier to
parse.

Updated graph_process_guard_data to run network.r

Created network.r to plot network data for each found network device.

### CODE REVIEW

**Comment by whirm** [comment]
Why isn't the newtork graph being generated?

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by whirm** [comment]
retest this please

**Comment by jdonkervliet** [comment]
I put a legend with my graph because I think it is important to be able to differentiate between network devices. The other graphs do not have this. Is this an issue?

**Comment by whirm** [comment]
No, that's perfect

**Comment by whirm** [comment]
Looks great, can you squash it in discrete commits?

**Comment by jdonkervliet** [comment]
Fixed.

**Pull request merged**
