### PR TITLE
Fixed dispersy bootstraptribler.txt path

### PR DESCRIPTION
**Pull request by NielsZeilemaker**

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
@whirm ready to be merged. Three points of worry, the trackers still connect to the outside world (which they shouldn't), the tracker logs aren't copied back during the jenkins testing, and finally the trackers don't seem to reply to the discovery community similarity-requests. 
I'm expecting them to do so, could you find out why trackers aren't working.

**Comment by whirm** [comment]
@NielsZeilemaker I will have a look. Could you squash the commits?

**Comment by NielsZeilemaker** [comment]
@whirm commits have been squashed

**Comment by whirm** [comment]
Thx.

**Pull request merged**
