### PR TITLE
Revert "Abort the tests once the first one fails to make the pull reques...

### PR DESCRIPTION
**Pull request by whirm**
Reverts Tribler/gumby#170

### CODE REVIEW

**Comment by whirm** [comment]
I've modified the pull request test job instead to let the devel branch job run the whole thing

**Comment by egbertbouman** [comment]
@whirm Did you test the pull request job after making these modifications?
It doesn't seem to be working any more.

**Comment by whirm** [comment]
you fixed that, right?

**Comment by egbertbouman** [comment]
Yeah, I just removed the '-x' option from the Jenkins job.

**Pull request merged**
