### PR TITLE
Update Gumby to work with new Tribler directory structure

### LINKED ISSUE #6807: validation_experiment_dht is broken
https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_dht

Probably, because of:
```python
INFO:ProcessRunner:[post_process_dht_exp...] ERR: Error in `combine_vars()`:
INFO:ProcessRunner:[post_process_dht_exp...] ERR: ! Faceting variables must have at least one value
INFO:ProcessRunner:[post_process_dht_exp...] ERR: Backtrace:
INFO:ProcessRunner:[post_process_dht_exp...] ERR:      ▆
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   1. └─ggplot2::ggsave(...)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   2.   ├─grid::grid.draw(plot)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   3.   └─ggplot2:::grid.draw.ggplot(plot)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   4.     ├─base::print(x)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   5.     └─ggplot2:::print.ggplot(x)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   6.       ├─ggplot2::ggplot_build(x)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   7.       └─ggplot2:::ggplot_build.ggplot(x)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   8.         └─layout$setup(data, plot$data, plot$plot_env)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:   9.           └─ggplot2 f(..., self = self)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:  10.             └─self$facet$compute_layout(data, self$facet_params)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:  11.               └─ggplot2 f(...)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:  12.                 └─ggplot2::combine_vars(data, params$plot_env, rows, drop = params$drop)
INFO:ProcessRunner:[post_process_dht_exp...] ERR:  13.                   └─rlang::abort("Faceting variables must have at least one value")
INFO:ProcessRunner:[post_process_dht_exp...] ERR: Execution halted
```

[full console output](https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_dht/1362/console)

### PR DESCRIPTION
**Pull request by kozlovsky**
Fixes [Tribler/gumby#6807](https://github.com/Tribler/tribler/issues/6807) by updating to a new Tribler package structure

### CODE REVIEW

**Comment by devos50** [comment]
Note that I modified the DAS5 experiment in the PR pipeline to accommodate for #514. I will revert this change to make sure this PR passes 👍

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Review by devos50 — APPROVED** [review]

**Pull request merged**
