### PR TITLE
Revert Windows/Mac tests automatic error exit state catching

### LINKED ISSUE #347: run_nosetests_for_jenkins.sh broken
The latest change (dd286713f0d36c545ab5198e7fd8b08977781c98) broke https://github.com/Tribler/gumby/blob/devel/scripts/run_nosetests_for_jenkins.sh for Windows and Mac.

For some reason this line:
https://github.com/Tribler/gumby/blob/dd286713f0d36c545ab5198e7fd8b08977781c98/scripts/run_nosetests_for_jenkins.sh#L160-L161
Does not properly split the space delimited `$pids` into different `p`, but instead outputs:
```
line 161: wait: ` 24496 24498 24500 24502 24504': not a pid or valid job spec
```

### PR DESCRIPTION
**Pull request by qstokkink**
~~This has been tested locally with the rest of the file intact (which is the reason why it is not working right now).~~

### CODE REVIEW

**Comment by devos50** [comment]
Ok, let me check this on the PR tester.

**Comment by devos50** [comment]
@qstokkink Still failing :/. On Windows, it gives:

```
strace.exe: error creating process trace=signal, (error 2)
```

On Mac, it cannot find the `strace` command (a quick google query hints that `dtruss` could be used instead on Mac?

**Comment by qstokkink** [comment]
@devos50 😢 I'm getting more and more in favor of just reverting these commits and performing manual inspection of the log files for the Windows/Mac tests.

**Comment by qstokkink** [comment]
@devos50 can you try this version (it uses wait instead of strace)?

**Comment by devos50** [comment]
@qstokkink sure, give me a moment

**Comment by qstokkink** [comment]
thanks 👍

**Comment by devos50** [comment]
On mac and windows: 

```
./gumby/scripts/run_nosetests_for_jenkins.sh: line 156: exec: 0: not found
```

**Comment by qstokkink** [comment]
@devos50 😭 see you in another hour

**Comment by devos50** [comment]
@qstokkink we can also revert it if you want 👍

**Comment by qstokkink** [comment]
@devos50 I'll give it a one or two more attempts, after that I think we should revert.

**Comment by qstokkink** [comment]
@devos50 screw it, let's revert.

**Comment by qstokkink** [comment]
@devos50 I reverted my changes, the approach we should probably take then is to inspect the .err/.out logs and see if an exit status string exists in it (in particular `wrap_in_temp_home.sh` prints out `exit $FAILURE` where `$FAILURE` is the exit status).

**Review by devos50 — APPROVED** [review]

**Pull request merged**
