### PR TITLE
Test PR for Jenkins job - do not merge

### PR DESCRIPTION
**Pull request by devos50**
This PR is used to test the new Jenkins job to run a basic Gumby experiment (also using it to get more familiar with the multijob plugin).

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by whirm** [comment]
What is this for? (the new testing job only listens to PRs to `master` to not confuse/annoy everybody with it)

**Comment by whirm** [comment]
Also there's a PR for testing purposes already.

**Comment by devos50** [comment]
This has nothing to do with the testing job on Tribler. I'm trying to run the basic experiment when a PR request is done to the Gumby repository to make it easier to verify that I don't break the basic experiment runner when making changes to Gumby. I try to do this with the same multi-job plugin that we are using for the Tribler repo (so we can easily add the pylint/dropme commits/print statements checkers later).

**Comment by devos50** [comment]
@whirm note that this one is on Gumby and not the Tribler repo ;)

**Comment by whirm** [comment]
Oh, lol, sorry :)

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Pull request closed without merging**
