### PR TITLE
Process historical dropped messages count

### PR DESCRIPTION
**Pull request by kc1212**
I plan to use https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin to retrieve data from previous successful builds (it's also what Laurens used).

The script works locally, the next step is to test it on Jenkins.

This is my first PR of actual code, so please let me know if you have any comments on the coding style/structure @devos50. Perhaps I should put the dropped message count specific stuff into its own class.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by kc1212** [comment]
@devos50 ready to be reviewed
some parameters need to be tuned, see the `DroppedStatsProcessor.process` method

**Comment by devos50** [comment]
@kc1212 looks ok.

Have you tested it by artificially creating a run with a huge number of dropped messages?

Also, please squash the commit history.

**Comment by kc1212** [comment]
@devos50 squashed the commit history
I tested it on an artificial `dropped_stats.json` that contains a huge number of dropped messages and it works fine. Is that okay or should I look into simulating dropped messages on the test clients (if that's possible)?

**Comment by kc1212** [comment]
I should mention that the Jenkins job needs to be amended for this to work, namely it needs an additional build step that copies the `dropped_stats.json` artifact from the previous build.

**Comment by devos50** [comment]
@kc1212 no need to do that. If you manually verified it, it's ok.

I will merge this PR. Can you change the AllChannels job and add the additional build step? Please don't run it again to save DAS5 nodes (it will run automatically tonight).

**Comment by kc1212** [comment]
@devos50 thanks, I'll do that now

**Pull request merged**
