### PR TITLE
Collecting network statistics.

### PR DESCRIPTION
**Pull request by jdonkervliet**
Collecting statistics from proc/net/dev

Untested.

### CODE REVIEW

**Comment by devos50** [comment]
add to whitelist

**Comment by whirm** [comment]
add to whitelist

**Comment by jdonkervliet** [comment]
I'll change the code to send the network output to a different file.
This makes sense because this data is not gathered per process but globally.
Sending the output to a different file also makes it more difficult to break the current code for the plots.

**Comment by jdonkervliet** [comment]
Done. A file called 'network-usage.log' is now used to monitor network traffic on all available network devices.
Network monitoring is only performed when the network flag (-n, --network) is passed to the process guard.

**Comment by whirm** [comment]
Looks good, can you squash it?

Will you update the plotting part in a future PR?

**Comment by jdonkervliet** [comment]
Squashed.

I would like to have the plots, so I'll update that in a later PR.

**Comment by whirm** [comment]
Great!

**Pull request merged**
