### PR TITLE
Major refactoring of several Gumby components

### PR DESCRIPTION
**Pull request by devos50**
In this PR, I performed a full refactor of the process guard statistics parser and made changes to the process guard and other scripts. In particular, I made the following changes:
- Removed the need for `psutil` in the process guard and fetching the number of threads from the `procfs` statistics instead.
- Removed scripts to reduce statistics. The motivation for this is as follows: the experiment duration is relative short (mostly under half an hour) and the number of data points generated in each plot is moderate. Besides, the reduce script was incredibly outdated and still contained logic to process stuff that Dispersy outputs. Therefore, I removed it.
- Separated the logic to parse `procfs` in a separate `ResourceUsageParser` class. This file has been fully refactored.
- Plotting the number of threads in a separate R script now.
- Included several plots to show the cumulative I/O operations throughput the experiment (see the output files `wchars_sum.png`, `rchars_sum.png`, `readbytes_sum.png` and `writebytes_sum.png`. This enables us to make statements on the total disk I/O performed during a single experiment.
- Clarified vertical axes of various plots.
- Added a DAS5 integration experiment to verify that a PR does not break any functionality when running on the DAS5.

### CODE REVIEW

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
retest this please

**Comment by devos50** [comment]
This PR is ready for review and I will use it as base for my DLT experiments to find possible bugs.

**Review by xoriole — APPROVED** [review]

**Pull request merged**
