### PR TITLE
Make sure self.network_monitor_file is defined in every conditional branch

### LINKED ISSUE #277: In process_guard.py, self.network_monitor_file is sometimes undefined.
In process_guard.py, self.network_monitor_file is sometimes undefined, crashing the whole thing.

```
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR: Traceback (most recent call last):
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR:   File "/home/jenkins/workspace/Experiment_multichain_100/gumby/scripts/process_guard.py", line 384, in <module>
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR:     exit(pm.monitoring_loop())
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR:   File "/home/jenkins/workspace/Experiment_multichain_100/gumby/scripts/process_guard.py", line 305, in monitoring_loop
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR:     if self.network_monitor_file:
INFO:OneShotProcessProtocol:[process_guard.py  -c...] ERR: AttributeError: 'ProcessMonitor' object has no attribute 'network_monitor_file'
INFO:OneShotProcessProtocol:[process_guard.py  -c...] OUT: No logger.conf found.
```

### PR DESCRIPTION
**Pull request by pimveldhuisen**
Fixes #277

### CODE REVIEW

**Comment by whirm** [comment]
add to whitelist

**Comment by devos50** [comment]
@pimveldhuisen can you rebase this PR?

**Comment by pimveldhuisen** [comment]
I have rebased, I failed to notice the comment earlier.

**Comment by devos50** [comment]
No problem :)

**Comment by devos50** [comment]
@pimveldhuisen it is better to define the `self.network_monitor_file` before the if/else statements so it's always available in the subsequent code. In this case, it is always defined and you can get rid of the else-case on line 244 and line 248, making the code slightly less complex.

Can you please do this? Then I wil merge it right away.

**Comment by pimveldhuisen** [comment]
@devos50 Done, I've done applied the same idea to the self.monitor_file, which has the same role.

**Comment by devos50** [comment]
Great!

**Pull request merged**
