### PR TITLE
Create script to build venv with dependencies

### PR DESCRIPTION
**Pull request by wouterjsmit**
Installs all dependencies as they are listed in a file
"requirements.txt" in the experiment directory.

### CODE REVIEW

**Comment by whirm** [comment]
Add some documentation so the config template generator finds the script and extract the relevant info please. (you can have a look at any of the scripts mentioned in the template config for the expected syntax)

**Comment by wouterjsmit** [comment]
Added a config option and commentary. Will the generator find it like this?

**Comment by whirm** [comment]
Yeah, that looks nice, I would mention that it uses VIRTUALENV_DIR too, squash it and I'll merge it.

**Comment by wouterjsmit** [comment]
Done!

**Pull request merged**
