### PR TITLE
Fix warnings in tests

### LINKED ISSUE #509: Warnings in the unit test output
We have a few warnings in the output of the unit tests:

```
=============================== warnings summary ===============================
gumby/experiment.py:1
  /home/jenkins/workspace/gumby/PR_tests_linux/gumby/gumby/experiment.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

gumby/experiment.py:6
  /home/jenkins/workspace/gumby/PR_tests_linux/gumby/gumby/experiment.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Iterable

gumby/scenario.py:53
  /home/jenkins/workspace/gumby/PR_tests_linux/gumby/gumby/scenario.py:53: DeprecationWarning: invalid escape sequence \$
    _re_substitution = re_compile("(\$\w+)")

gumby/scenario.py:54
  /home/jenkins/workspace/gumby/PR_tests_linux/gumby/gumby/scenario.py:54: DeprecationWarning: invalid escape sequence \w
    _re_preprocessor_dir = re_compile("^&(\w+)\s+")

gumby/scenario.py:55
  /home/jenkins/workspace/gumby/PR_tests_linux/gumby/gumby/scenario.py:55: DeprecationWarning: invalid escape sequence \s
    _re_named_arg = re_compile("^\s*(\w+)\s*=\s*(.*)$")
```

These warnings should be relatively straightforward to fix.

### PR DESCRIPTION
**Pull request by kozlovsky**
Fixes #509. Better to merge after #508 is merged

### CODE REVIEW

**Comment by devos50** [comment]
@kozlovsky what's the status of this PR?

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
@devos50 the PR itself is ready, Pylint Jenkins's job seems to be broken, it fails with the following exception in the `diff-quality` tool:

```
Traceback (most recent call last):
  File "/usr/local/bin/diff-quality", line 8, in <module>
    sys.exit(main())
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/diff_quality_tool.py", line 348, in main
    percent_passing = generate_quality_report(
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/diff_quality_tool.py", line 261, in generate_quality_report
    reporter.generate_report(output_file)
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 265, in generate_report
    report = template.render(self._context())
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 314, in _context
    context = super().report_dict()
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 187, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 84, in src_paths
    for src, summary in self._diff_violations().items()
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    self._diff_violations_dict = {
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/report_generator.py", line 178, in <dictcomp>
    self._violations.violations(src_path),
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/violationsreporters/base.py", line 159, in violations
    self.violations_dict.update(self.driver.parse_reports([output]))
  File "/home/jenkins/.local/lib/python3.8/site-packages/diff_cover/violationsreporters/violations_reporter.py", line 469, in parse_reports
    violation = Violation(int(line_number), error_str)
ValueError: invalid literal for int() with base 10: '470]'
```

I'm investigating that, hopefully it can be fixed

**Comment by kozlovsky** [comment]
retest this please

**Comment by kozlovsky** [comment]
The `diff-quality` bug should be fixed in https://github.com/Bachmann1234/diff_cover/pull/277, I manually updated the server code for now to fix the issue. Now the Jenkins job works again

**Review by devos50 — APPROVED** [review]
Thanks!

**Pull request merged**
