### PR TITLE
Refactor for get_member() changes in dispersy

### PR DESCRIPTION
**Pull request by whirm**
This needs to be merged at the same time than https://github.com/Tribler/dispersy/pull/233

### CODE REVIEW

**Comment by whirm** [comment]
@NielsZeilemaker Ready!

**Comment by NielsZeilemaker** [comment]
is this change backwards compatible?

**Comment by whirm** [comment]
It won't work with an old dispersy if we pass the private key only.
Do you want to keep backwards compatiblity here? It would only matter if we where to run run das4 experiments with a new gumby and an old dispersy.

https://github.com/Tribler/dispersy/pull/233/files#diff-6ca8135667b3a3cb278e4383ff45d89cL522

Before we where forced to pass the public key even when passing the private/public keypair

**Comment by NielsZeilemaker** [comment]
You're basically describing all jenkins experiments we have except yours, allchannel, demers, etc are all using gumby/devel + tribler/devel + dispersy/next

**Comment by whirm** [comment]
I've undone the merge, let's talk about it when I'm back

**Pull request merged**
