### PR TITLE
Use print() function and sys.maxsize() both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__print()__ is a function in Python 3.

### CODE REVIEW

**Comment by devos50** [comment]
ok to test

**Comment by devos50** [comment]
@cclauss did you accept the invitation for the Tribler organization?

**Comment by cclauss** [comment]
Yes.

**Comment by devos50** [comment]
add to whitelist

**Comment by devos50** [comment]
@cclauss while we do not have very strict rules for pull requests on the Gumby project, could you have a look at the pylint issues?

Also, I will consider adding the Python 3 flake regression to Gumby 👍

**Comment by devos50** [comment]
Also, a quick look at the code changes suggest that you did more than changing print statements. Could you update your title to reflect these changes?

**Comment by devos50** [comment]
@cclauss if this PR is ready, please let me know so I can run your PR on a bigger experiment 👍

**Comment by devos50** [comment]
Seems to work fine! https://jenkins-ci.tribler.org/job/validation_experiments/job/validation_experiment_trustchain/262/

I will review the PR now.

**Review by devos50 — APPROVED** [review]
Looks good! Please clean up your commit history and I will merge the PR.

**Comment by devos50** [comment]
Thanks!

**Pull request merged**
